version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: rohitsingirikondamongodb:v1
    container_name: mongodb
  redis:
    image: rohitsingirikondaredis
  catalogue:
    image: rohitsingirikondacatalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: rohitsingirikondauser:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: rohitsingirikondacart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue 
  ratings:
    image: rohitsingirikondaratings:v1
    container_name: ratings
    depends_on:
    - catalogue
  mysql:
    image: rohitsingirikondamysql:v1
    container_name: mysql
  shipping:
    image: rohitsingirikondashipping:v1
    container_name: shipping
    depends_on:
    - mysql
  payment:
    image: rohitsingirikondapayment:v1
    container_name: payment
    depends_on:
    - shipping  
  web:
    image: rohitsingirikondaweb:v1
    container_name: web
    ports:
      - 80:80
    depends_on:
    - catalogue
    - cart
    - user
    - mysql
    - shipping
    - payment

#docker-compose up -d