version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  redis:
    image: redis
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue 
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
    - catalogue
  mysql:
    image: mysql:v1
    container_name: mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - shipping  
  web:
    image: web:v1
    container_name: web
    ports:
      - 80:80
    depends_on:
    - catalogue
    - cart
    - user
    - mysql
    - shipping
    - payment

#docker-compose up -d