version: "3.9"
networks:
  roboshop:
    driver: bridge
volumes:
 # This is equalant to docker volume create [volume-name], called Named Volumes are preferred than unanomouns volumes.
  mysql:
    driver: local 
    driver_opts:
      o: bind
      type: none
      device: /root/roboshop_volumes/mysql
  mongodb:
    driver: local 
    driver_opts:
      o: bind
      type: none
      device: /root/roboshop_volumes/mongodb
  rabbitmq:
    driver: local 
    driver_opts:
      o: bind
      type: none
      device: /root/roboshop_volumes/rabbitmq
  redis:
    driver: local 
    driver_opts:
      o: bind
      type: none
      device: /root/roboshop_volumes/redis            
services:
  mongodb:
    image: rohitsingirikonda/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis
    container_name: redis
    volumes:
    - mongodb:/data
  mysql:
    image: rohitsingirikonda/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  catalogue:
    image: rohitsingirikonda/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: rohitsingirikonda/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: rohitsingirikonda/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue 
  ratings:
    image: rohitsingirikonda/ratings:v1
    container_name: ratings
    depends_on:
    - catalogue
  shipping:
    image: rohitsingirikonda/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  payment:
    image: rohitsingirikonda/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq 
  web:
    image: rohitsingirikonda/web:v1
    container_name: web
    ports:
      - 80:80
    depends_on:
    - catalogue
    - cart
    - user
    - mysql
    - shipping
    - payment

#docker-compose up -d