version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: rohitsingirikonda/mongodb:v1
    container_name: mongodb
  redis:
    image: redis
  catalogue:
    image: rohitsingirikonda/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: rohitsingirikonda/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: rohitsingirikonda/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue 
  ratings:
    image: rohitsingirikonda/ratings:v1
    container_name: ratings
    depends_on:
    - catalogue
  mysql:
    image: rohitsingirikonda/mysql:v1
    container_name: mysql
  shipping:
    image: rohitsingirikonda/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  payment:
    image: rohitsingirikonda/payment:v1
    container_name: payment
    depends_on:
    - shipping  
  web:
    image: rohitsingirikonda/web:v1
    container_name: web
    ports:
      - 80:80
    depends_on:
    - catalogue
    - cart
    - user
    - mysql
    - shipping
    - payment

#docker-compose up -d