version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  redis:
    image: redis
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis 
  web:
    image: web:v1
    container_name: web
    depends_on:
    - catalogue
